[[unicorn]]
arch = "x86_64"
git-tree-sha1 = "ba804ce4c2dc5dbed00c4d367581c5a982fffdc3"
libc = "glibc"
os = "linux"

    [[unicorn.download]]
    sha256 = "d5018d4256a5c8393b3723a0c1839c24280adbc14572bd6d88009bd6f655a501"
    url = "https://github.com/oblivia-simplex/unicorn_jll/raw/main/unicorn.v1.0.0.x86_64-linux-gnu.tar.gz"
